### PR TITLE
add missing saftey trip

### PR DESCRIPTION
**Pull request by ZacLN**

### CODE REVIEW

**Comment by davidanthoff** [comment]
Ok, I would say we'll merge this as soon as we have a v0.16 build out in the release channel, i.e. first patch build after that I'll merge this, ok?

I'm going to assign this one to myself, just so that it shows up as one of the things I should merge once the timing is right.

**Comment by pfitzseb** [comment]
I'd almost be in favour of including this in the current release...

**Comment by davidanthoff** [comment]
I just want to get v0.16 out, and then we can go back to our usual schedule of almost daily releases and include this in one of those. But if we add this right now, we need to reset our insider test clock, and there is a risk that this might introduce another problem, which would further set us back?

Plus, even if we include it, we won't be able to fix this bug pre v0.16 public release, because then we'll need another release that actually fixes things once we've identified the problem. _And_, it might also that the problem is in LanguagServer.jl, which we haven't diagnosed yet... To me this problem looks like one we won't be able to fix super soon.

**Comment by pfitzseb** [comment]
Fair enough.

**Pull request merged**
