### PR TITLE
fix char parsing

### PR DESCRIPTION
**Pull request by pfitzseb**
Fixes https://github.com/julia-vscode/julia-vscode/issues/2186.

For every PR, please check the following:
- [x] End-user documentation check. If this PR requires end-user documentation in the Julia VS Code extension docs, please add that at https://github.com/julia-vscode/docs.
- [ ] Changelog mention. If this PR should be mentioned in the CHANGELOG for the Julia VS Code extension, please open a PR against https://github.com/julia-vscode/julia-vscode/blob/master/CHANGELOG.md with those changes.

### CODE REVIEW

**Review by davidanthoff — DISMISSED** [review]

**Comment by davidanthoff** [comment]
Hm, this seems to not work on Julia 1.0?

**Review by davidanthoff — DISMISSED** [review]
There are a lot of whitespace changes in here as well? No problem, but maybe there is a setting that would avoid that?

**Comment by pfitzseb** [comment]
Yes, but I like my files better without trailing whitespace ;)

**Comment by pfitzseb** [comment]
Turns out our string parsing was broken in the presence of invalid escape sequences in strings, so this PR fixes that as well.

**Review by davidanthoff — APPROVED** [review]

**Pull request merged**
