### PR TITLE
Tweaks for refactored julia internal parser interface

### PR DESCRIPTION
**Pull request by c42f**
The flisp parser is now available via Core.Compiler.fl_parse rather than
via a ccall to jl_parse_string. jl_parse_string will redirect to
Core._parse, which may be CSTParser if the Julia parser has been
overridden.

See the upstream PR for details of the internal changes to the Julia runtime
https://github.com/JuliaLang/julia/pull/35243

### CODE REVIEW

**Comment by davidanthoff** [comment]
Please hold off merging this until we are finished with the VS Code release plans we have for this week.

**Comment by ZacLN** [comment]
No worries, I saw your notice!

**Comment by davidanthoff** [comment]
What is the status of this?

**Comment by c42f** [comment]
Waiting for review

**Pull request merged**
