### PR TITLE
More errparse

### PR DESCRIPTION
**Pull request by pfitzseb**
Might help with finding something for https://github.com/julia-vscode/crashreporting-issues/issues/39 or https://github.com/julia-vscode/crashreporting-issues/issues/48 in the future.

Tests might be too slow now though and didn't find anything locally.

### CODE REVIEW

**Review by davidanthoff — APPROVED** [review]

**Comment by davidanthoff** [comment]
Failures seem real?

**Comment by pfitzseb** [comment]
Yes, but I can't repro it locally by running our tests on the failing case printed in the test...

**Comment by davidanthoff** [comment]
Do we not merge it then?

**Comment by pfitzseb** [comment]
Yep. Should figure out what goes wrong here first.

**Pull request closed without merging**
